echo Running admin.py tests.....
@python admin/test_admin.py
echo Running event.py tests.....
@python event/test_event.py
echo Running fullSUser.py tests.....
@python fullSUser/test_fsUser.py
echo Running user.py tests.....
@python user/test_user.py
@pause